# ===================================================================
# CONFIGURAÇÃO DE PORTA DO SERVIDOR (SIMULADO 1)
# ===================================================================
server.port=8081

# ===================================================================
# OPÇÃO 1: BANCO DE DADOS H2 EM MEMÓRIA (PADRÃO ATIVO)
# Não necessita instalar nem configurar nada, sobe automaticamente.
# ===================================================================
spring.datasource.url=jdbc:mysql://localhost:3306/simulado?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# ===================================================================
# OPÇÃO 2: BANCO DE DADOS MYSQL (OPCIONAL)
# Para usar MySQL:
# 1) Descomente as linhas abaixo e comente o bloco do H2 acima.
# 2) Crie o banco no MySQL com: CREATE DATABASE investimentodb;
# 3) Ajuste usuario e senha conforme sua instalacao local.
# ===================================================================
# spring.datasource.url=jdbc:mysql://localhost:3306/investimentodb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
# spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
# spring.datasource.username=root
# spring.datasource.password=root123
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# ===================================================================
# CONFIGURAÇÃO DE SEGURANÇA JWT (CHAVE CRIPTOGRÁFICA SEGURA 256 BITS)
# ===================================================================
jwt.secret=minhaChaveSuperSecretaParaAssinaturaJwtDeInvestimentosEAtividades2026!
jwt.expiration=86400000
