spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/investimento
spring.datasource.username=root
spring.datasource.password=
# Criação da Tabela
spring.jpa.hibernate.ddl-auto=update
